/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudando;

import java.awt.Font;

/**
 *
 * @author Admin
 */
public class Revisando extends javax.swing.JFrame {

    /**
     * Creates new form Revisando
     */
    public Revisando() {
        initComponents();
        lblFrase.setText("<html>Estou pensando em um numero de 0 a 5. Tente advinhar...</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JSpinner();
        ntnPalpite = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Area de Trabalho hd\\IMAGENS\\NetBeans\\SHAR.4799.252.2.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 280, 385));

        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frease");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Area de Trabalho hd\\IMAGENS\\NetBeans\\balaozinho.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 390, 240));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 20));

        ntnPalpite.setText("Tentar");
        ntnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(ntnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ntnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntnPalpiteActionPerformed
        // TODO add your handling code here:
     double ale = 0 + Math.random() * (5 - 0);
     int num = (int) ale;
   
     int n = Integer.parseInt(txtNum.getValue().toString());
     
     String t1 = "ACERTOU MISERAVII";
     String t2 = "ERROU, ESTAVA PENSANDO EM ";
     
     
     String res = (n==num)?t1:t2 + num;
     lblFrase.setFont(new Arial Black, Font.ITALIC, 22));
     lblFrase.setText(res);
    }//GEN-LAST:event_ntnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revisando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JButton ntnPalpite;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
